editor: source

execute:
  cache: false
  freeze: false

project:
  type: website
  output-dir: docs
  render: [index.qmd]
  post-render: "R/_post-render.R"

title: "Prediction and Interaction in ABMs"
author: "Daniel Vartanian"
keyword: >
  Complexity science, Agent-based modeling, Individual-Based Models,
  Bottom-up modeling, Prediction, Interaction, Simulation,
  Sensitivity analysis, Scenario analysis, Nonlinear systems
institute: "University of São Paulo"
date: 2025-04-15
date-format: "DD/MM/YYYY"

website:
  favicon: images/favicon.svg
  site-url: https://danielvartan.github.io/abm-study-group-pres-2/
  repo-url: https://github.com/danielvartan/abm-study-group-pres-2/
  issue-url: https://github.com/danielvartan/abm-study-group-pres-2/issues/
  open-graph:
    image: images/og-image.png
    image-width: 2400
    image-height: 1600
    image-alt: Sustentarea Research and Extension Group
  repo-branch: main

format:
  revealjs:
    locale: en
    lang: en
    echo: true
    code-link: true
    code-fold: false
    link-external-newwindow: true
    tbl-cap-location: top
    callout-appearance: simple
    csl: csl/english-apa-author-date.csl
    preview-links: false
    controls: true
    controls-layout: bottom-right
    chalkboard: true
    auto-stretch: true
    fig-align: center
    theme: [default, brand, scss/styles.scss]
    pdf-max-pages-per-slide: 1
    template-partials:
      - html/title-slide.html
    menu:
      titleSelector: [h1 h2]
      useTextContentForMissingTitles: false
      hideMissingTitles: false
    include-in-header:
      text: |
        <meta property="og:description" content="">
        <meta property="og:image" content="/abm-study-group-pres-2/images/og-image.png">
        <meta property="og:image:height" content="2400">
        <meta property="og:image:width" content="1600">

google-scholar: false
bibliography: references.bib
nocite: "@*"
